# Generated by Django 4.2.3 on 2023-07-19 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(default=datetime.timezone)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='gateway.device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
